services:
  trade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --strategy E0V1E_53
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json

  backtesting:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      backtesting
      --config /freqtrade/user_data/config.json
      --strategy E0V1E_53
      --timerange 20241019-20241025 -i 5m


  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      download-data
      --exchange binance
      --timerange 20240101-
      --config /freqtrade/user_data/config.json
      --pairs BTC/USDT ETH/USDT ADA/USDT SOL/USDT XRP/USDT AVAX/USDT SAND/USDT FTM/USDT ICP/USDT ALICE/USDT RAY/USDT DOT/USDT FTT/USDT AXS/USDT ATA/USDT C98/USDT CELO/USDT LRC/USDT XTZ/USDT AR/USDT ETC/USDT MBOX/USDT CHR/USDT LINK/USDT ATOM/USDT CHZ/USDT EOS/USDT AUDIO/USDT KAVA/USDT LTC/USDT BCH/USDT ENJ/USDT KSM/USDT NEAR/USDT THETA/USDT CAKE/USDT FARM/USDT MANA/USDT TRX/USDT RUNE/USDT MASK/USDT OGN/USDT UNI/USDT GTC/USDT BAKE/USDT EGLD/USDT FLOW/USDT COTI/USDT SUSHI/USDT SXP/USDT PERP/USDT DEGO/USDT GRT/USDT

  test-pairlist:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      test-pairlist
      --config /freqtrade/user_data/config.json
      --quote USDT
