services:
  trade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --strategy ElliotV5_SMA
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json

  backtesting:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      backtesting
      --config /freqtrade/user_data/config-backtest.json
      --strategy ElliotV5_SMA
      --timerange 20241019-20241023 -i 5m


  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      download-data
      --exchange binance
      --timerange 20240901-
      --config /freqtrade/user_data/config.json
      --pairs BTC/USDT SOL/USDT ETH/USDT DOGE/USDT NEIRO/USDT SCR/USDT APT/USDT APE/USDT SUI/USDT XRP/USDT ALPHA/USDT PEPE/USDT WIF/USDT UNI/USDT RUNE/USDT PIXEL/USDT BONK/USDT WLD/USDT BOME/USDT LINK/USDT CATI/USDT NEAR/USDT AVAX/USDT ENA/USDT FTM/USDT SEI/USDT FLOKI/USDT DYDX/USDT SHIB/USDT TAO/USDT RAY/USDT TRX/USDT

  test-pairlist:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      test-pairlist
      --config /freqtrade/user_data/config.json
      --quote USDT
