#!/bin/bash

mkdir -p ./user_data/logs

function trade() {
  # trade
  docker compose up -d trade
}

function stop_trade() {
  # stop trade
  docker compose down
}

function test_pairlist() {
  # test-pairlist
  docker compose run --rm test-pairlist
}

function download_data() {
  # download-data
  docker compose run --rm download-data
}

function backtesting() {
  # backtesting
  docker compose run --rm backtesting
}

function print_args() {
  echo "wrong arg"
  echo ""
  echo "trade               : start trading"
  echo "stop                : stop trading"
  echo "-p, --test-pairlist : get test pairlist"
  echo "-d, --download-data : download trading data"
  echo "-b, --backtesting   : backtesting"
  return -1
}
###

for arg in "$@"; do
  if [[ "$arg" = trade ]]; then
    trade
  elif [[ "$arg" = stop ]]; then
    stop_trade
  elif [[ "$arg" = -p ]] || [[ "$arg" = --test-pairlist ]]; then
    test_pairlist
  elif [[ "$arg" = -d ]] || [[ "$arg" = --download-data ]]; then
    download_data
  elif [[ "$arg" = -b ]] || [[ "$arg" = --backtesting ]]; then
    backtesting
  else
    print_args
  fi
done
